config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :boletos do
    member do
      put :cancel
    end
  end

  root to: 'boletos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boleto.rb
class Boleto < ApplicationRecord
  validates :amount, :expire_at, :customer_person_name, :customer_cnpj_cpf, :customer_state, :customer_city_name,
            :customer_zipcode, :customer_address, :customer_neighborhood, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boletos_controller.rb
class BoletosController < ApplicationController
  before_action :set_kobana_service

  def index
    @boletos = @kobana_service.list_boletos
  end

  def create
    response = @kobana_service.create_boleto(boleto_params)
    @boleto = response
    handle_create_response(response)
  end

  def update
    prepare_update_params
    response = @kobana_service.update_boleto(params[:id], boleto_params.to_h, @user_agent, @idempotency_key)
    handle_update_response(response)
  rescue JSON::ParserError => e
    log_error(e.message)
    redirect_to boletos_url, alert: 'An error occurred while processing the response.'
  rescue StandardError => e
    log_error(e.message)
    redirect_to boletos_url, alert: 'An unexpected error occurred.'
  end

  def cancel
    response = @kobana_service.cancel_boleto(params[:id], params[:cancellation_reason])
    handle_cancel_response(response)
  end

  def edit
    @boleto = @kobana_service.get_boleto(params[:id])
    redirect_to boletos_url, alert: 'Boleto not found' if @boleto.blank?
  end

  private

  def set_kobana_service
    @kobana_service = KobanaService.new
  end

  def prepare_update_params
    @user_agent = 'your_email@example.com'
    @idempotency_key = SecureRandom.uuid
    process_boleto_tags
    process_days_for_sue
  end

  def process_boleto_tags
    params[:boleto][:tags] = params[:boleto][:tags].split(',').map(&:strip) if params[:boleto][:tags].is_a?(String)
  end

  def process_days_for_sue
    params[:boleto][:days_for_sue] = params[:boleto][:days_for_sue].to_i if params[:boleto][:days_for_sue].is_a?(String)
  end

  def handle_create_response(response)
    respond_to do |format|
      if response['status'] == 'success'
        format.html { redirect_to boletos_url, notice: 'Boleto was successfully created.' }
        format.json { render :show, status: :created, location: @boleto }
      else
        format.html do
          redirect_to boletos_url, alert: response['message'] || 'An error occurred while creating the boleto.'
        end
        format.json { render json: response, status: :unprocessable_entity }
      end
    end
  end

  def handle_update_response(response)
    respond_to do |format|
      if response['status'] == 'success'
        format.html { redirect_to boletos_url, notice: 'Boleto was successfully updated.' }
        format.json { render :show, status: :ok, location: @boleto }
      else
        format.html do
          redirect_to boletos_url, alert: response['message'] || 'An error occurred while updating the boleto.'
        end
        format.json { render json: response, status: :unprocessable_entity }
      end
    end
  end

  def handle_cancel_response(response)
    respond_to do |format|
      if response['status'] == 'success'
        format.html { redirect_to boletos_url, notice: 'Boleto was successfully cancelled.' }
        format.json { head :no_content }
      else
        format.html { redirect_to boletos_url, alert: response['message'] || 'Failed to cancel boleto.' }
        format.json { render json: response, status: :unprocessable_entity }
      end
    end
  end

  def log_error(message)
    Rails.logger.error "Error: #{message}"
  end

  def boleto_params
    params.require(:boleto).permit(
      :amount, :expire_at, :customer_person_name, :customer_cnpj_cpf,
      :customer_state, :customer_city_name, :customer_neighborhood,
      :customer_address, :notes, :days_for_sue, :sue_code, :instructions,
      :description, :reduction_amount, tags: []
    ).tap do |sanitized_params|
      if sanitized_params[:customer_zipcode]
        sanitized_params[:customer_zipcode] =
          sanitized_params[:customer_zipcode].gsub(/[^0-9]/, '')
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boletos_helper.rb
module BoletosHelper
end

app/views/boletos/_boleto.html.erb
<div id="<%= dom_id boleto %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Codigo:</strong>
    <%= boleto.codigo %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Vencimento:</strong>
    <%= boleto.vencimento %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Valor:</strong>
    <%= boleto.valor %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this boleto", boleto, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this boleto", edit_boleto_path(boleto), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/boletos/_form.html.erb
<%= form_with(model: boleto, class: "contents") do |form| %>
  <% if boleto.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(boleto.errors.count, "error") %> prohibited this boleto from being saved:</h2>

      <ul>
        <% boleto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :codigo %>
    <%= form.text_field :codigo, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :vencimento %>
    <%= form.date_field :vencimento, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :valor %>
    <%= form.text_field :valor, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/boletos/edit.html.erb
<% if @boleto %>
  <div class="max-w-md mx-auto bg-white shadow-md overflow-hidden sm:rounded-lg lg:max-w-4xl mb-8">
    <div class="px-4 py-5 sm:px-6">
      <h2 class="text-lg font-semibold text-gray-800">Edit Boleto</h2>
    </div>
    <div class="border-t border-gray-200">
      <%= form_for :boleto, url: boleto_path(@boleto['id']), method: :put, id: "edit_boleto_form" do |f| %>
        <div class="p-6 grid grid-cols-1 gap-6 sm:grid-cols-2">
          <div>
            <%= f.label :amount, "Amount", class: "block font-medium text-sm text-gray-700" %>
            <%= f.number_field :amount, value: sprintf('%.2f', @boleto['amount']), step: '0.01', class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
          </div>
          
          <div>
            <%= f.label :expire_at, "Expire At", class: "block font-medium text-sm text-gray-700" %>
            <%= f.date_field :expire_at, value: @boleto['expire_at'], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :tags, "Tags", class: "block font-medium text-sm text-gray-700" %>
            <%= f.text_field :tags, value: @boleto['tags'].join(', '), class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :notes, "Notes", class: "block font-medium text-sm text-gray-700" %>
            <%= f.text_area :notes, value: @boleto['notes'], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>

          <div>
            <%= f.label :days_for_sue, "Days for Sue", class: "block font-medium text-sm text-gray-700" %>
            <%= f.number_field :days_for_sue, value: @boleto['days_for_sue'], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>

          <div>
            <%= f.label :sue_code, "Sue Code", class: "block font-medium text-sm text-gray-700" %>
            <%= f.text_field :sue_code, value: @boleto['sue_code'], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :instructions, "Instructions", class: "block font-medium text-sm text-gray-700" %>
            <%= f.text_area :instructions, value: @boleto['instructions'], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :description, "Description", class: "block font-medium text-sm text-gray-700" %>
            <%= f.text_area :description, value: @boleto['description'], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>

          <div>
            <%= f.label :reduction_amount, "Reduction Amount", class: "block font-medium text-sm text-gray-700" %>
            <%= f.number_field :reduction_amount, value: @boleto['reduction_amount'], class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
          </div>

          <!-- Buttons aligned to the left -->
          <div class="sm:col-span-2 text-left">
            <%= f.submit "Update Boleto", class: "inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
            <%= link_to 'Go Back', root_path, class: 'inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-gray-700 bg-gray-200 hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <p>Boleto not found.</p>
<% end %>

app/views/boletos/index.html.erb
<div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
  <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
    <div class="p-6 bg-white border-b border-gray-200">
      <h2 class="text-2xl font-semibold text-gray-800 mb-4">Boletos</h2>

      <div class="mb-2 sm:mb-0 pb-5">
        <%= link_to 'New Boleto', new_boleto_path, class: 'bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded' %>
      </div>

      <div class="flex flex-col sm:flex-row justify-between mb-4">
        <% if @boletos.any? %>
          <table class="min-w-full divide-y divide-gray-200 shadow-sm overflow-x-auto">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Bank Bilet Account ID</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Our Number</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Processed Our Number</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">CNPJ/CPF</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Expire Date</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Paid Date</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% @boletos.each do |boleto| %>
                <tr>
                  <td class="px-6 py-4 whitespace-nowrap"><%= boleto['bank_billet_account_id'] %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= boleto['status'] %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= boleto['our_number'] %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= boleto['processed_our_number_raw'] %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= boleto['customer_cnpj_cpf'] %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= boleto['expire_at'] %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= boleto['paid_at'] || 'N/A' %></td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <% if boleto['status'].downcase != 'canceled' %>
                      <%= link_to 'Edit', edit_boleto_path(boleto['id']), class: 'inline-block bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded', data: { turbo_frame: 'boleto-edit', remote: true } %>
                      <button data-boleto-id="<%= boleto['id'] %>" class="delete-btn inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-2">
                        Delete
                      </button>
                    <% else %>
                      <%= link_to 'Edit', edit_boleto_path(boleto['id']), class: 'inline-block bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded pointer-events-none opacity-50 cursor-not-allowed', data: { turbo_frame: 'boleto-edit', remote: true } %>
                      <button class="delete-btn inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-2 pointer-events-none opacity-50 cursor-not-allowed" disabled>
                        Delete
                      </button>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p class="text-gray-500">No boletos found.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal Structure -->
<div id="deleteModal" class="fixed z-10 inset-0 overflow-y-auto hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>
    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
      <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
        <div class="sm:flex sm:items-start">
          <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
            <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">Cancel Boleto</h3>
            <div class="mt-2">
              <p class="text-sm text-gray-500">Select the cancellation reason:</p>
              <%= form_with url: cancel_boleto_path(0), method: :put, id: "cancelBoletoForm" do |form| %>
                <div class="mb-3"> <!-- Dropdown wrapper -->
                  <%= select_tag :cancellation_reason, options_for_select([['Outro', 1], ['Fraude', 2], ['Óbito', 3], ['Erro operacional', 4], ['Quitação paga', 5]]), class: "rounded-md block w-full" %>
                </div>
                <%= hidden_field_tag :id, nil, id: "boletoId" %>
                <div class="text-left"> <!-- Button wrapper -->
                  <%= submit_tag 'Cancel Boleto', class: 'bg-red-600 text-white font-bold py-2 px-4 rounded cursor-pointer' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
        <button type="button" class="modal-close mt-3 w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  document.querySelectorAll('.delete-btn').forEach(button => {
    button.addEventListener('click', function() {
      const boletoId = this.getAttribute('data-boleto-id');
      document.getElementById('boletoId').value = boletoId;
      const form = document.getElementById('cancelBoletoForm');
      form.action = `/boletos/${boletoId}/cancel`;
      document.getElementById('deleteModal').classList.remove('hidden');
    });
  });

  document.querySelectorAll('.modal-close').forEach(button => {
    button.addEventListener('click', function() {
      document.getElementById('deleteModal').classList.add('hidden');
    });
  });
</script>

app/views/boletos/new.html.erb
<%= form_for :boleto, url: boletos_path, method: :post, id: "new_boleto_form" do |f| %>
  <div class="max-w-md mx-auto bg-white shadow-md overflow-hidden sm:rounded-lg lg:max-w-4xl mb-8">
    <div class="px-4 py-5 sm:px-6">
      <h2 class="text-lg font-semibold text-gray-800">New Boleto</h2>
    </div>
    <div class="border-t border-gray-200">
      <div class="p-6 grid grid-cols-1 gap-6 sm:grid-cols-2">
        <!-- Amount -->
        <div>
          <%= f.label :amount, "Amount", class: "block font-medium text-sm text-gray-700" %>
          <%= f.number_field :amount, step: '0.01', class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
        </div>

        <!-- Expire At -->
        <div>
          <%= f.label :expire_at, "Expire At", class: "block font-medium text-sm text-gray-700" %>
          <%= f.date_field :expire_at, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
        </div>

        <!-- Customer Person Name -->
        <div class="sm:col-span-2">
          <%= f.label :customer_person_name, "Customer Person Name", class: "block font-medium text-sm text-gray-700" %>
          <%= f.text_field :customer_person_name, maxlength: 120, placeholder: "Full Name", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
        </div>

        <!-- Customer CNPJ/CPF -->
        <div class="sm:col-span-2">
          <%= f.label :customer_cnpj_cpf, "Customer CNPJ/CPF", class: "block font-medium text-sm text-gray-700" %>
          <%= f.text_field :customer_cnpj_cpf, minlength: 11, maxlength: 20, placeholder: "12345678901234", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
        </div>

        <!-- Customer State -->
        <div>
          <%= f.label :customer_state, "Customer State", class: "block font-medium text-sm text-gray-700" %>
          <%= f.select :customer_state, options_for_select(['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']), {}, { class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" } %>
        </div>

        <!-- Customer City Name -->
        <div>
          <%= f.label :customer_city_name, "Customer City Name", class: "block font-medium text-sm text-gray-700" %>
          <%= f.text_field :customer_city_name, id: "boleto_customer_city_name", maxlength: 60, placeholder: "City Name", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
        </div>

        <!-- Customer Zipcode -->
        <div class="sm:col-span-2">
          <%= f.label :customer_zipcode, "Customer Zipcode", class: "block font-medium text-sm text-gray-700" %>
          <%= f.text_field :customer_zipcode, minlength: 8, maxlength: 10, placeholder: '99999999', title: "Zipcode should be 8 digits without any hyphens or spaces", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>

        </div>

        <!-- Customer Address -->
        <div class="sm:col-span-2">
          <%= f.label :customer_address, "Customer Address", class: "block font-medium text-sm text-gray-700" %>
          <%= f.text_field :customer_address, maxlength: 255, placeholder: "1234 Main St", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
        </div>

        <!-- Customer Neighborhood -->
        <div class="sm:col-span-2">
          <%= f.label :customer_neighborhood, "Customer Neighborhood", class: "block font-medium text-sm text-gray-700" %>
          <%= f.text_field :customer_neighborhood, maxlength: 80, placeholder: "Neighborhood", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", required: true %>
        </div>

        <!-- Buttons aligned to the left -->
        <div class="sm:col-span-2 text-left"> <!-- Change here for alignment -->
          <%= f.submit "Create Boleto", class: "inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
          <%= link_to 'Go Back', root_path, class: 'inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-gray-700 bg-gray-200 hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  let autocomplete;

  function initAutocomplete() {
    const customerCityNameField = document.querySelector("#boleto_customer_city_name");

    // Initialize the Google Places Autocomplete with restrictions to Latin American countries
    autocomplete = new google.maps.places.Autocomplete(customerCityNameField, {
      componentRestrictions: { country: ["ar", "bo", "br", "cl", "co", "cr", "cu", "do", "ec", "sv", "gt", "gy", "hn", "ht", "jm", "mx", "ni", "pa", "py", "pe", "pr", "sr", "tt", "uy", "ve", "bz", "bs", "bb"] },
      fields: ["address_components"],
      types: ["(cities)"],
    });

    autocomplete.addListener("place_changed", () => {
      const place = autocomplete.getPlace();
      let cityName = "";
      for (const component of place.address_components) {
        if (component.types.includes("locality")) {
          cityName = component.long_name;
          break;
        }
      }
      customerCityNameField.value = cityName;
    });
  }

  window.initAutocomplete = initAutocomplete;
</script>

app/views/boletos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @boleto %>

    <%= link_to "Edit this boleto", edit_boleto_path(@boleto), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this boleto", boleto_path(@boleto), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to boletos", boletos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('fav.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBs3tyLZooZ0_Lm0XEesbDUDuCM27d9R8s&libraries=places&callback=initAutocomplete" async defer></script>
  </head>
  <body class="bg-gray-500">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>